### PR TITLE
Present Proof v3

### PR DESCRIPTION
**Pull request by TelegramSam**
v2, adapted for DIDComm v2

### CODE REVIEW

**Comment by TimoGlastra** [comment]
Welp, just worked out v3 and see you already did it...

Anyhow, looks like they're almost similar except that I chose to include a `proposal_attach_ids`, `request_attach_ids` and `presentation_attach_ids` to specify the attachments that are intended for the presentation exchange (instead of other attachments not related to the exchange). I guess `format` would be sufficient for that.

[https://hackmd.io/@animo/Hk3jYFe3_](https://hackmd.io/@animo/Hk3jYFe3_)

**Comment by OR13** [comment]
@TelegramSam @TimoGlastra can you take your remaining deltas to issues and cross link them back here?

**Review by OR13 — APPROVED** [review]
Looks good to me

**Comment by OR13** [comment]
We agreed to merge this PR as is, and discuss any related issues separately

**Pull request merged**
