### PR TITLE
adding in strawmen of explanatory text for each section in multiple commits

### PR DESCRIPTION
**Pull request by bumblefudge**
Trying to get something (anything!) up for various issues as per this week's call, for discussing/refining on next week's.

### CODE REVIEW

**Comment by bumblefudge** [comment]
^ commit for issues #24 & #25

**Comment by bumblefudge** [comment]
^ commit with tweaks to prior commit and adding verbiage for #20

**Comment by bumblefudge** [comment]
^ commit for #21

**Comment by bumblefudge** [comment]
^ commit for #22 

BUT at this point in my process I realized I didn't understand anything and needed to ask some questions at the next meeting.  I've collected them in #22

**Comment by OR13** [comment]
please address conflicts

**Comment by bumblefudge** [comment]
addresseded, still want to discuss on call today tho!

**Review by brentzundel — APPROVED** [review]

**Pull request merged**
