### PR TITLE
Focus spec for v0.1

### PR DESCRIPTION
**Pull request by OR13**
- remove offer/ claim (for now)
- remove credential manifest (for now)

### CODE REVIEW

**Comment by OR13** [comment]
@JaceHensley please tag anyone at bloom who might have an opinion.

We want to clean up the spec up for v0.1 and then add the didcomm messages, and test vectors for Presentation Exchange test vectors.

**Review by brentzundel — APPROVED** [review]

**Comment by OR13** [comment]
For the record, the group assumes that we will need to add sections or pointers regarding what is getting taken out of this PR back in, eventually, these changes are just to help us get a stable version rev.

**Comment by TelegramSam** [comment]
LGTM

**Review by kdenhartog — APPROVED** [review]
Make sense to remove this now

**Review by JaceHensley — APPROVED** [review]

**Comment by brentzundel** [comment]
multiple positive reviews, merging

**Pull request merged**
